platform :ios, '8.0'

pod 'AFNetworking'
pod 'MBProgressHUD', '~> 0.8'
pod 'NSDateMinimalTimeAgo', '~> 0.1.0'
pod 'SVPullToRefresh'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBSDKMessengerShareKit'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'JSQMessagesViewController'
pod 'Firebase'

